/*
 * gui.c
 * 
 * Copyright 2014 Mikael Wågberg <mickew@ubuntu-vm>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */


#include "support.h"

const char *sGui =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.24\"/>"
"  <object class=\"GtkWindow\" id=\"main_window\">"
"    <property name=\"width_request\">400</property>"
"    <property name=\"can_focus\">False</property>"
"    <property name=\"border_width\">5</property>"
"    <property name=\"title\" translatable=\"yes\">VPN Config</property>"
"    <property name=\"resizable\">False</property>"
"    <property name=\"window_position\">center</property>"
"    <property name=\"default_width\">400</property>"
"    <property name=\"icon\">icon.png</property>"
"    <signal name=\"destroy\" handler=\"gtk_main_quit\" swapped=\"no\"/>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"can_focus\">False</property>"
"        <property name=\"spacing\">2</property>"
"        <child>"
"          <object class=\"GtkVBox\" id=\"vbox2\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">False</property>"
"            <property name=\"spacing\">3</property>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"spacing\">2</property>"
"                <child>"
"                  <object class=\"GtkLabel\" id=\"lblhost\">"
"                    <property name=\"width_request\">70</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">False</property>"
"                    <property name=\"tooltip_markup\">Host name or IP</property>"
"                    <property name=\"label\" translatable=\"yes\">Host:</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkEntry\" id=\"tbhost\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"invisible_char\">•</property>"
"                    <property name=\"primary_icon_activatable\">False</property>"
"                    <property name=\"secondary_icon_activatable\">False</property>"
"                    <property name=\"primary_icon_sensitive\">True</property>"
"                    <property name=\"secondary_icon_sensitive\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">True</property>"
"                <property name=\"fill\">True</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox2\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"spacing\">2</property>"
"                <child>"
"                  <object class=\"GtkLabel\" id=\"lblgroupname\">"
"                    <property name=\"width_request\">70</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">False</property>"
"                    <property name=\"label\" translatable=\"yes\">Group Name:</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkEntry\" id=\"tbgroupname\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"invisible_char\">•</property>"
"                    <property name=\"primary_icon_activatable\">False</property>"
"                    <property name=\"secondary_icon_activatable\">False</property>"
"                    <property name=\"primary_icon_sensitive\">True</property>"
"                    <property name=\"secondary_icon_sensitive\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">True</property>"
"                <property name=\"fill\">True</property>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox3\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"spacing\">2</property>"
"                <child>"
"                  <object class=\"GtkLabel\" id=\"lblgrouppassword\">"
"                    <property name=\"width_request\">70</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">False</property>"
"                    <property name=\"label\" translatable=\"yes\">Group Password:</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkEntry\" id=\"tbgrouppassword\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"visibility\">False</property>"
"                    <property name=\"primary_icon_activatable\">False</property>"
"                    <property name=\"secondary_icon_activatable\">False</property>"
"                    <property name=\"primary_icon_sensitive\">True</property>"
"                    <property name=\"secondary_icon_sensitive\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">True</property>"
"                <property name=\"fill\">True</property>"
"                <property name=\"position\">2</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox4\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"spacing\">2</property>"
"                <child>"
"                  <object class=\"GtkLabel\" id=\"lblusername\">"
"                    <property name=\"width_request\">70</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">False</property>"
"                    <property name=\"label\" translatable=\"yes\">User Name:</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkEntry\" id=\"tbusername\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"invisible_char\">•</property>"
"                    <property name=\"primary_icon_activatable\">False</property>"
"                    <property name=\"secondary_icon_activatable\">False</property>"
"                    <property name=\"primary_icon_sensitive\">True</property>"
"                    <property name=\"secondary_icon_sensitive\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">True</property>"
"                <property name=\"fill\">True</property>"
"                <property name=\"position\">3</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkHBox\" id=\"hbox5\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"spacing\">2</property>"
"                <child>"
"                  <object class=\"GtkLabel\" id=\"lbluserpassword\">"
"                    <property name=\"width_request\">70</property>"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">False</property>"
"                    <property name=\"label\" translatable=\"yes\">User Password:</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">0</property>"
"                  </packing>"
"                </child>"
"                <child>"
"                  <object class=\"GtkEntry\" id=\"tbuserpassword\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"visibility\">False</property>"
"                    <property name=\"primary_icon_activatable\">False</property>"
"                    <property name=\"secondary_icon_activatable\">False</property>"
"                    <property name=\"primary_icon_sensitive\">True</property>"
"                    <property name=\"secondary_icon_sensitive\">True</property>"
"                  </object>"
"                  <packing>"
"                    <property name=\"expand\">True</property>"
"                    <property name=\"fill\">True</property>"
"                    <property name=\"position\">1</property>"
"                  </packing>"
"                </child>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">True</property>"
"                <property name=\"fill\">True</property>"
"                <property name=\"position\">4</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">True</property>"
"            <property name=\"fill\">True</property>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">False</property>"
"            <property name=\"spacing\">2</property>"
"            <property name=\"layout_style\">end</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"btncancel\">"
"                <property name=\"label\" translatable=\"yes\">Cancel</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_action_appearance\">False</property>"
"                <signal name=\"clicked\" handler=\"gtk_main_quit\" swapped=\"no\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkButton\" id=\"btnok\">"
"                <property name=\"label\" translatable=\"yes\">Ok</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_action_appearance\">False</property>"
"                <signal name=\"clicked\" handler=\"on_btnok_clicked\" swapped=\"no\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">True</property>"
"            <property name=\"fill\">True</property>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>";
